/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.saltsoft;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        PierwszaKlasa a = new PierwszaKlasa();
        a.readLinesFromFile("U:\\dev\\Czytanie\\src\\main\\java\\pl\\saltsoft\\App.java");
        a.writeFile("readme.md");

      
    }




}
