/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.saltsoft;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        Koty koty = new Koty("Puszek", 5.5, 1);

        Serializer b = new Serializer();
        b.serialize(koty);

        String jsonkoty = "{\"name\":\"Puszek\",\"waga\":5.5,\"ilosc\":1}";

        Koty kotek = b.deserialize(jsonkoty);
        System.out.println (kotek.name);

    }


}
